// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.tripdocs.model;

import net.triptech.tripdocs.model.Preferences;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Preferences_Roo_Configurable {
    
    declare @type: Preferences: @Configurable;
    
}
