// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.triptech.tripdocs.model;

import net.triptech.tripdocs.model.PersonIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PersonIntegrationTest_Roo_Configurable {
    
    declare @type: PersonIntegrationTest: @Configurable;
    
}
